# Generated by Django 4.0.3 on 2022-04-04 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='lat',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='lng',
            field=models.FloatField(verbose_name='Долгота'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер фото')),
                ('img', models.ImageField(upload_to='', verbose_name='Фото')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place', verbose_name='Координаты')),
            ],
        ),
    ]
