# Generated by Django 4.0.3 on 2022-04-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_coordinates_lat_alter_coordinates_lng_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='placeid',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название места'),
        ),
    ]
