# Generated by Django 4.0.3 on 2022-04-06 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='places.place', verbose_name='Координаты'),
        ),
    ]
