# Generated by Django 4.0.3 on 2022-04-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_coordinates_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['sort']},
        ),
        migrations.AddField(
            model_name='image',
            name='sort',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='image',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Позиция'),
        ),
    ]
