# Generated by Django 4.0.3 on 2022-04-08 11:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_image_options_remove_image_sort_place_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='title',
            field=tinymce.models.HTMLField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
