# Generated by Django 4.0.3 on 2022-04-18 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_alter_place_description_long_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='placeid',
        ),
    ]
