# Generated by Django 4.0.3 on 2022-05-04 10:22

from django.db import migrations


def replace_descriptions(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    for place in Place.objects.all():
        if not place.description_short:
            place.description_short = ''
            place.save()
        if not place.description_long:
            place.description_long = ''
            place.save()


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_remove_place_placeid'),
    ]

    operations = [
        migrations.RunPython(replace_descriptions),
    ]
