# Generated by Django 4.0.3 on 2022-05-04 11:50

from django.db import migrations


def replace_coordinates(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    for place in Place.objects.all():
        if not place.lng:
            place.lat = 0
            place.save()
        if not place.lat:
            place.lat = 0
            place.save()


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_auto_20220504_1022'),
    ]

    operations = [
        migrations.RunPython(replace_coordinates),
    ]
